####
# Run: docker run --rm -v $(pwd):/usr/src/app my-c-project
####
# Use an official base image
FROM debian:latest

# Install build essentials for C (gcc, make, etc.)
RUN apt-get update && apt-get install -qq -y build-essential

# Set the working directory in the container
WORKDIR /usr/src/app

# Command to run when the container starts
CMD ["make", "test"]


